<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Sample" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="interaction" src="dialog/interaction/interaction.dlg" />
    </Dialogs>
    <Resources>
        <File name="app" src="html/css/app.css" />
        <File name="default" src="html/css/default.css" />
        <File name="reset" src="html/css/reset.css" />
        <File name="index" src="html/index.html" />
        <File name="Sample" src="Sample.phpproj" />
        <File name="adjust" src="html/js/adjust.js" />
        <File name="se_quiz_failure" src="html/audio/se_quiz_failure.ogg" />
        <File name="se_quiz_start" src="html/audio/se_quiz_start.ogg" />
        <File name="se_quiz_success" src="html/audio/se_quiz_success.ogg" />
        <File name="bgm" src="html/audio/bgm.ogg" />
        <File name="app" src="app.cnf" />
        <File name="Sample" src="Sample.sln" />
        <File name="contents" src="html/js/contents.js" />
        <File name="tapper" src="html/js/tapper.js" />
        <File name="tapper_audio" src="html/js/tapper_audio.js" />
        <File name="bg_common" src="html/images/preloads/bg_common.png" />
        <File name="bg_splash" src="html/images/preloads/bg_splash.png" />
        <File name="text_correct" src="html/images/preloads/text_correct.png" />
        <File name="text_incorrect" src="html/images/preloads/text_incorrect.png" />
        <File name="se_btn_touched" src="html/audio/se_btn_touched.ogg" />
        <File name="tapper_preview" src="html/js/tapper_preview.js" />
        <File name="se_recognize_end" src="html/audio/se_recognize_end.ogg" />
        <File name="se_recognize_start" src="html/audio/se_recognize_start.ogg" />
        <File name="samplegooglevision" src="samplegooglevision.phpproj" />
        <File name="__init__" src="libs/apiclient/__init__.py" />
        <File name="DESCRIPTION" src="libs/google_api_python_client-1.6.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/google_api_python_client-1.6.4.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/google_api_python_client-1.6.4.dist-info/METADATA" />
        <File name="RECORD" src="libs/google_api_python_client-1.6.4.dist-info/RECORD" />
        <File name="WHEEL" src="libs/google_api_python_client-1.6.4.dist-info/WHEEL" />
        <File name="metadata" src="libs/google_api_python_client-1.6.4.dist-info/metadata.json" />
        <File name="top_level" src="libs/google_api_python_client-1.6.4.dist-info/top_level.txt" />
        <File name="__init__" src="libs/googleapiclient/__init__.py" />
        <File name="_auth" src="libs/googleapiclient/_auth.py" />
        <File name="channel" src="libs/googleapiclient/channel.py" />
        <File name="discovery" src="libs/googleapiclient/discovery.py" />
        <File name="__init__" src="libs/googleapiclient/discovery_cache/__init__.py" />
        <File name="appengine_memcache" src="libs/googleapiclient/discovery_cache/appengine_memcache.py" />
        <File name="base" src="libs/googleapiclient/discovery_cache/base.py" />
        <File name="file_cache" src="libs/googleapiclient/discovery_cache/file_cache.py" />
        <File name="errors" src="libs/googleapiclient/errors.py" />
        <File name="http" src="libs/googleapiclient/http.py" />
        <File name="mimeparse" src="libs/googleapiclient/mimeparse.py" />
        <File name="model" src="libs/googleapiclient/model.py" />
        <File name="sample_tools" src="libs/googleapiclient/sample_tools.py" />
        <File name="schema" src="libs/googleapiclient/schema.py" />
        <File name="PKG-INFO" src="libs/httplib2-0.10.3-py2.7.egg-info/PKG-INFO" />
        <File name="SOURCES" src="libs/httplib2-0.10.3-py2.7.egg-info/SOURCES.txt" />
        <File name="dependency_links" src="libs/httplib2-0.10.3-py2.7.egg-info/dependency_links.txt" />
        <File name="installed-files" src="libs/httplib2-0.10.3-py2.7.egg-info/installed-files.txt" />
        <File name="top_level" src="libs/httplib2-0.10.3-py2.7.egg-info/top_level.txt" />
        <File name="__init__" src="libs/httplib2/__init__.py" />
        <File name="cacerts" src="libs/httplib2/cacerts.txt" />
        <File name="iri2uri" src="libs/httplib2/iri2uri.py" />
        <File name="socks" src="libs/httplib2/socks.py" />
        <File name="DESCRIPTION" src="libs/oauth2client-4.1.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/oauth2client-4.1.2.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/oauth2client-4.1.2.dist-info/METADATA" />
        <File name="RECORD" src="libs/oauth2client-4.1.2.dist-info/RECORD" />
        <File name="WHEEL" src="libs/oauth2client-4.1.2.dist-info/WHEEL" />
        <File name="metadata" src="libs/oauth2client-4.1.2.dist-info/metadata.json" />
        <File name="top_level" src="libs/oauth2client-4.1.2.dist-info/top_level.txt" />
        <File name="__init__" src="libs/oauth2client/__init__.py" />
        <File name="_helpers" src="libs/oauth2client/_helpers.py" />
        <File name="_openssl_crypt" src="libs/oauth2client/_openssl_crypt.py" />
        <File name="_pkce" src="libs/oauth2client/_pkce.py" />
        <File name="_pure_python_crypt" src="libs/oauth2client/_pure_python_crypt.py" />
        <File name="_pycrypto_crypt" src="libs/oauth2client/_pycrypto_crypt.py" />
        <File name="client" src="libs/oauth2client/client.py" />
        <File name="clientsecrets" src="libs/oauth2client/clientsecrets.py" />
        <File name="__init__" src="libs/oauth2client/contrib/__init__.py" />
        <File name="_appengine_ndb" src="libs/oauth2client/contrib/_appengine_ndb.py" />
        <File name="_metadata" src="libs/oauth2client/contrib/_metadata.py" />
        <File name="appengine" src="libs/oauth2client/contrib/appengine.py" />
        <File name="devshell" src="libs/oauth2client/contrib/devshell.py" />
        <File name="dictionary_storage" src="libs/oauth2client/contrib/dictionary_storage.py" />
        <File name="__init__" src="libs/oauth2client/contrib/django_util/__init__.py" />
        <File name="apps" src="libs/oauth2client/contrib/django_util/apps.py" />
        <File name="decorators" src="libs/oauth2client/contrib/django_util/decorators.py" />
        <File name="models" src="libs/oauth2client/contrib/django_util/models.py" />
        <File name="signals" src="libs/oauth2client/contrib/django_util/signals.py" />
        <File name="site" src="libs/oauth2client/contrib/django_util/site.py" />
        <File name="storage" src="libs/oauth2client/contrib/django_util/storage.py" />
        <File name="views" src="libs/oauth2client/contrib/django_util/views.py" />
        <File name="flask_util" src="libs/oauth2client/contrib/flask_util.py" />
        <File name="gce" src="libs/oauth2client/contrib/gce.py" />
        <File name="keyring_storage" src="libs/oauth2client/contrib/keyring_storage.py" />
        <File name="multiprocess_file_storage" src="libs/oauth2client/contrib/multiprocess_file_storage.py" />
        <File name="sqlalchemy" src="libs/oauth2client/contrib/sqlalchemy.py" />
        <File name="xsrfutil" src="libs/oauth2client/contrib/xsrfutil.py" />
        <File name="crypt" src="libs/oauth2client/crypt.py" />
        <File name="file" src="libs/oauth2client/file.py" />
        <File name="service_account" src="libs/oauth2client/service_account.py" />
        <File name="tools" src="libs/oauth2client/tools.py" />
        <File name="transport" src="libs/oauth2client/transport.py" />
        <File name="DESCRIPTION" src="libs/pyasn1-0.4.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/pyasn1-0.4.2.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/pyasn1-0.4.2.dist-info/METADATA" />
        <File name="RECORD" src="libs/pyasn1-0.4.2.dist-info/RECORD" />
        <File name="WHEEL" src="libs/pyasn1-0.4.2.dist-info/WHEEL" />
        <File name="metadata" src="libs/pyasn1-0.4.2.dist-info/metadata.json" />
        <File name="top_level" src="libs/pyasn1-0.4.2.dist-info/top_level.txt" />
        <File name="zip-safe" src="libs/pyasn1-0.4.2.dist-info/zip-safe" />
        <File name="__init__" src="libs/pyasn1/__init__.py" />
        <File name="__init__" src="libs/pyasn1/codec/__init__.py" />
        <File name="__init__" src="libs/pyasn1/codec/ber/__init__.py" />
        <File name="decoder" src="libs/pyasn1/codec/ber/decoder.py" />
        <File name="encoder" src="libs/pyasn1/codec/ber/encoder.py" />
        <File name="eoo" src="libs/pyasn1/codec/ber/eoo.py" />
        <File name="__init__" src="libs/pyasn1/codec/cer/__init__.py" />
        <File name="decoder" src="libs/pyasn1/codec/cer/decoder.py" />
        <File name="encoder" src="libs/pyasn1/codec/cer/encoder.py" />
        <File name="__init__" src="libs/pyasn1/codec/der/__init__.py" />
        <File name="decoder" src="libs/pyasn1/codec/der/decoder.py" />
        <File name="encoder" src="libs/pyasn1/codec/der/encoder.py" />
        <File name="__init__" src="libs/pyasn1/codec/native/__init__.py" />
        <File name="decoder" src="libs/pyasn1/codec/native/decoder.py" />
        <File name="encoder" src="libs/pyasn1/codec/native/encoder.py" />
        <File name="__init__" src="libs/pyasn1/compat/__init__.py" />
        <File name="binary" src="libs/pyasn1/compat/binary.py" />
        <File name="calling" src="libs/pyasn1/compat/calling.py" />
        <File name="dateandtime" src="libs/pyasn1/compat/dateandtime.py" />
        <File name="integer" src="libs/pyasn1/compat/integer.py" />
        <File name="octets" src="libs/pyasn1/compat/octets.py" />
        <File name="string" src="libs/pyasn1/compat/string.py" />
        <File name="debug" src="libs/pyasn1/debug.py" />
        <File name="error" src="libs/pyasn1/error.py" />
        <File name="__init__" src="libs/pyasn1/type/__init__.py" />
        <File name="base" src="libs/pyasn1/type/base.py" />
        <File name="char" src="libs/pyasn1/type/char.py" />
        <File name="constraint" src="libs/pyasn1/type/constraint.py" />
        <File name="error" src="libs/pyasn1/type/error.py" />
        <File name="namedtype" src="libs/pyasn1/type/namedtype.py" />
        <File name="namedval" src="libs/pyasn1/type/namedval.py" />
        <File name="opentype" src="libs/pyasn1/type/opentype.py" />
        <File name="tag" src="libs/pyasn1/type/tag.py" />
        <File name="tagmap" src="libs/pyasn1/type/tagmap.py" />
        <File name="univ" src="libs/pyasn1/type/univ.py" />
        <File name="useful" src="libs/pyasn1/type/useful.py" />
        <File name="DESCRIPTION" src="libs/pyasn1_modules-0.2.1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/pyasn1_modules-0.2.1.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/pyasn1_modules-0.2.1.dist-info/METADATA" />
        <File name="RECORD" src="libs/pyasn1_modules-0.2.1.dist-info/RECORD" />
        <File name="WHEEL" src="libs/pyasn1_modules-0.2.1.dist-info/WHEEL" />
        <File name="metadata" src="libs/pyasn1_modules-0.2.1.dist-info/metadata.json" />
        <File name="top_level" src="libs/pyasn1_modules-0.2.1.dist-info/top_level.txt" />
        <File name="zip-safe" src="libs/pyasn1_modules-0.2.1.dist-info/zip-safe" />
        <File name="__init__" src="libs/pyasn1_modules/__init__.py" />
        <File name="pem" src="libs/pyasn1_modules/pem.py" />
        <File name="rfc1155" src="libs/pyasn1_modules/rfc1155.py" />
        <File name="rfc1157" src="libs/pyasn1_modules/rfc1157.py" />
        <File name="rfc1901" src="libs/pyasn1_modules/rfc1901.py" />
        <File name="rfc1902" src="libs/pyasn1_modules/rfc1902.py" />
        <File name="rfc1905" src="libs/pyasn1_modules/rfc1905.py" />
        <File name="rfc2251" src="libs/pyasn1_modules/rfc2251.py" />
        <File name="rfc2314" src="libs/pyasn1_modules/rfc2314.py" />
        <File name="rfc2315" src="libs/pyasn1_modules/rfc2315.py" />
        <File name="rfc2437" src="libs/pyasn1_modules/rfc2437.py" />
        <File name="rfc2459" src="libs/pyasn1_modules/rfc2459.py" />
        <File name="rfc2511" src="libs/pyasn1_modules/rfc2511.py" />
        <File name="rfc2560" src="libs/pyasn1_modules/rfc2560.py" />
        <File name="rfc3279" src="libs/pyasn1_modules/rfc3279.py" />
        <File name="rfc3280" src="libs/pyasn1_modules/rfc3280.py" />
        <File name="rfc3281" src="libs/pyasn1_modules/rfc3281.py" />
        <File name="rfc3412" src="libs/pyasn1_modules/rfc3412.py" />
        <File name="rfc3414" src="libs/pyasn1_modules/rfc3414.py" />
        <File name="rfc3447" src="libs/pyasn1_modules/rfc3447.py" />
        <File name="rfc3852" src="libs/pyasn1_modules/rfc3852.py" />
        <File name="rfc4210" src="libs/pyasn1_modules/rfc4210.py" />
        <File name="rfc4211" src="libs/pyasn1_modules/rfc4211.py" />
        <File name="rfc5208" src="libs/pyasn1_modules/rfc5208.py" />
        <File name="rfc5280" src="libs/pyasn1_modules/rfc5280.py" />
        <File name="rfc5652" src="libs/pyasn1_modules/rfc5652.py" />
        <File name="rfc6402" src="libs/pyasn1_modules/rfc6402.py" />
        <File name="DESCRIPTION" src="libs/rsa-3.4.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/rsa-3.4.2.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/rsa-3.4.2.dist-info/METADATA" />
        <File name="RECORD" src="libs/rsa-3.4.2.dist-info/RECORD" />
        <File name="WHEEL" src="libs/rsa-3.4.2.dist-info/WHEEL" />
        <File name="entry_points" src="libs/rsa-3.4.2.dist-info/entry_points.txt" />
        <File name="metadata" src="libs/rsa-3.4.2.dist-info/metadata.json" />
        <File name="top_level" src="libs/rsa-3.4.2.dist-info/top_level.txt" />
        <File name="__init__" src="libs/rsa/__init__.py" />
        <File name="_compat" src="libs/rsa/_compat.py" />
        <File name="_version133" src="libs/rsa/_version133.py" />
        <File name="_version200" src="libs/rsa/_version200.py" />
        <File name="asn1" src="libs/rsa/asn1.py" />
        <File name="bigfile" src="libs/rsa/bigfile.py" />
        <File name="cli" src="libs/rsa/cli.py" />
        <File name="common" src="libs/rsa/common.py" />
        <File name="core" src="libs/rsa/core.py" />
        <File name="key" src="libs/rsa/key.py" />
        <File name="parallel" src="libs/rsa/parallel.py" />
        <File name="pem" src="libs/rsa/pem.py" />
        <File name="pkcs1" src="libs/rsa/pkcs1.py" />
        <File name="prime" src="libs/rsa/prime.py" />
        <File name="randnum" src="libs/rsa/randnum.py" />
        <File name="transform" src="libs/rsa/transform.py" />
        <File name="util" src="libs/rsa/util.py" />
        <File name="varblock" src="libs/rsa/varblock.py" />
        <File name="DESCRIPTION" src="libs/six-1.11.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/six-1.11.0.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/six-1.11.0.dist-info/METADATA" />
        <File name="RECORD" src="libs/six-1.11.0.dist-info/RECORD" />
        <File name="WHEEL" src="libs/six-1.11.0.dist-info/WHEEL" />
        <File name="metadata" src="libs/six-1.11.0.dist-info/metadata.json" />
        <File name="top_level" src="libs/six-1.11.0.dist-info/top_level.txt" />
        <File name="six" src="libs/six.py" />
        <File name="DESCRIPTION" src="libs/uritemplate-3.0.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/uritemplate-3.0.0.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/uritemplate-3.0.0.dist-info/METADATA" />
        <File name="RECORD" src="libs/uritemplate-3.0.0.dist-info/RECORD" />
        <File name="WHEEL" src="libs/uritemplate-3.0.0.dist-info/WHEEL" />
        <File name="metadata" src="libs/uritemplate-3.0.0.dist-info/metadata.json" />
        <File name="top_level" src="libs/uritemplate-3.0.0.dist-info/top_level.txt" />
        <File name="__init__" src="libs/uritemplate/__init__.py" />
        <File name="api" src="libs/uritemplate/api.py" />
        <File name="template" src="libs/uritemplate/template.py" />
        <File name="variable" src="libs/uritemplate/variable.py" />
        <File name="samplegooglevision" src="samplegooglevision.sln" />
    </Resources>
    <Topics>
        <Topic name="interaction_jpj" src="dialog/interaction/interaction_jpj.top" topicName="interaction" language="ja_JP" />
    </Topics>
    <IgnoredPaths />
    <Translations auto-fill="ja_JP">
        <Translation name="translation_ja_JP" src="translations/translation_ja_JP.ts" language="ja_JP" />
    </Translations>
</Package>
