<?xml version="1.0" encoding="UTF-8" ?>
<Package name="026" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="interaction" src="dialog/interaction/interaction.dlg" />
    </Dialogs>
    <Resources>
        <File name="app" src="app.cnf" />
        <File name="Sample" src="Sample.phpproj" />
        <File name="Sample" src="Sample.sln" />
        <File name="samplegooglevision" src="samplegooglevision.phpproj" />
        <File name="samplegooglevision" src="samplegooglevision.sln" />
        <File name="applicationhost" src=".vs/config/applicationhost.config" />
        <File name="" src=".vs/Sample/v14/.suo" />
        <File name="" src=".vs/samplegooglevision/v14/.suo" />
        <File name="index" src="html/index.html" />
        <File name="bgm" src="html/audio/bgm.ogg" />
        <File name="se_btn_touched" src="html/audio/se_btn_touched.ogg" />
        <File name="se_quiz_failure" src="html/audio/se_quiz_failure.ogg" />
        <File name="se_quiz_start" src="html/audio/se_quiz_start.ogg" />
        <File name="se_quiz_success" src="html/audio/se_quiz_success.ogg" />
        <File name="se_recognize_end" src="html/audio/se_recognize_end.ogg" />
        <File name="se_recognize_start" src="html/audio/se_recognize_start.ogg" />
        <File name="app" src="html/css/app.css" />
        <File name="default" src="html/css/default.css" />
        <File name="reset" src="html/css/reset.css" />
        <File name="photo" src="html/images/photo.jpg" />
        <File name="bg_common" src="html/images/preloads/bg_common.png" />
        <File name="bg_splash" src="html/images/preloads/bg_splash.png" />
        <File name="text_correct" src="html/images/preloads/text_correct.png" />
        <File name="text_incorrect" src="html/images/preloads/text_incorrect.png" />
        <File name="adjust" src="html/js/adjust.js" />
        <File name="contents" src="html/js/contents.js" />
        <File name="tapper" src="html/js/tapper.js" />
        <File name="tapper_audio" src="html/js/tapper_audio.js" />
        <File name="tapper_preview" src="html/js/tapper_preview.js" />
        <File name="six" src="libs/six.py" />
        <File name="__init__" src="libs/apiai/__init__.py" />
        <File name="apiai" src="libs/apiai/apiai.py" />
        <File name="resampler" src="libs/apiai/resampler.py" />
        <File name="VAD" src="libs/apiai/VAD.py" />
        <File name="__init__" src="libs/apiai/requests/__init__.py" />
        <File name="request" src="libs/apiai/requests/request.py" />
        <File name="__init__" src="libs/apiai/requests/query/__init__.py" />
        <File name="events" src="libs/apiai/requests/query/events.py" />
        <File name="query" src="libs/apiai/requests/query/query.py" />
        <File name="text" src="libs/apiai/requests/query/text.py" />
        <File name="voice" src="libs/apiai/requests/query/voice.py" />
        <File name="__init__" src="libs/apiai/requests/user_entities/__init__.py" />
        <File name="user_entities_request" src="libs/apiai/requests/user_entities/user_entities_request.py" />
        <File name="DESCRIPTION" src="libs/apiai-1.2.3.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/apiai-1.2.3.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/apiai-1.2.3.dist-info/METADATA" />
        <File name="metadata" src="libs/apiai-1.2.3.dist-info/metadata.json" />
        <File name="RECORD" src="libs/apiai-1.2.3.dist-info/RECORD" />
        <File name="top_level" src="libs/apiai-1.2.3.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/apiai-1.2.3.dist-info/WHEEL" />
        <File name="__init__" src="libs/apiclient/__init__.py" />
        <File name="f2py" src="libs/bin/f2py.py" />
        <File name="DESCRIPTION" src="libs/google_api_python_client-1.6.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/google_api_python_client-1.6.4.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/google_api_python_client-1.6.4.dist-info/METADATA" />
        <File name="metadata" src="libs/google_api_python_client-1.6.4.dist-info/metadata.json" />
        <File name="RECORD" src="libs/google_api_python_client-1.6.4.dist-info/RECORD" />
        <File name="top_level" src="libs/google_api_python_client-1.6.4.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/google_api_python_client-1.6.4.dist-info/WHEEL" />
        <File name="__init__" src="libs/googleapiclient/__init__.py" />
        <File name="_auth" src="libs/googleapiclient/_auth.py" />
        <File name="channel" src="libs/googleapiclient/channel.py" />
        <File name="discovery" src="libs/googleapiclient/discovery.py" />
        <File name="errors" src="libs/googleapiclient/errors.py" />
        <File name="http" src="libs/googleapiclient/http.py" />
        <File name="mimeparse" src="libs/googleapiclient/mimeparse.py" />
        <File name="model" src="libs/googleapiclient/model.py" />
        <File name="sample_tools" src="libs/googleapiclient/sample_tools.py" />
        <File name="schema" src="libs/googleapiclient/schema.py" />
        <File name="__init__" src="libs/googleapiclient/discovery_cache/__init__.py" />
        <File name="appengine_memcache" src="libs/googleapiclient/discovery_cache/appengine_memcache.py" />
        <File name="base" src="libs/googleapiclient/discovery_cache/base.py" />
        <File name="file_cache" src="libs/googleapiclient/discovery_cache/file_cache.py" />
        <File name="file_cache" src="libs/googleapiclient/discovery_cache/file_cache.pyc" />
        <File name="__init__" src="libs/httplib2/__init__.py" />
        <File name="cacerts" src="libs/httplib2/cacerts.txt" />
        <File name="iri2uri" src="libs/httplib2/iri2uri.py" />
        <File name="socks" src="libs/httplib2/socks.py" />
        <File name="dependency_links" src="libs/httplib2-0.10.3-py2.7.egg-info/dependency_links.txt" />
        <File name="installed-files" src="libs/httplib2-0.10.3-py2.7.egg-info/installed-files.txt" />
        <File name="PKG-INFO" src="libs/httplib2-0.10.3-py2.7.egg-info/PKG-INFO" />
        <File name="SOURCES" src="libs/httplib2-0.10.3-py2.7.egg-info/SOURCES.txt" />
        <File name="top_level" src="libs/httplib2-0.10.3-py2.7.egg-info/top_level.txt" />
        <File name="__config__" src="libs/numpy/__config__.py" />
        <File name="__init__" src="libs/numpy/__init__.py" />
        <File name="_distributor_init" src="libs/numpy/_distributor_init.py" />
        <File name="_globals" src="libs/numpy/_globals.py" />
        <File name="_import_tools" src="libs/numpy/_import_tools.py" />
        <File name="add_newdocs" src="libs/numpy/add_newdocs.py" />
        <File name="conftest" src="libs/numpy/conftest.py" />
        <File name="ctypeslib" src="libs/numpy/ctypeslib.py" />
        <File name="dual" src="libs/numpy/dual.py" />
        <File name="LICENSE" src="libs/numpy/LICENSE.txt" />
        <File name="matlib" src="libs/numpy/matlib.py" />
        <File name="setup" src="libs/numpy/setup.py" />
        <File name="version" src="libs/numpy/version.py" />
        <File name="libopenblas.UWVN3XTD2LSS7SFIFK6TIQ5GONFDBJKU.gfortran-win32" src="libs/numpy/.libs/libopenblas.UWVN3XTD2LSS7SFIFK6TIQ5GONFDBJKU.gfortran-win32.dll" />
        <File name="__init__" src="libs/numpy/compat/__init__.py" />
        <File name="_inspect" src="libs/numpy/compat/_inspect.py" />
        <File name="py3k" src="libs/numpy/compat/py3k.py" />
        <File name="setup" src="libs/numpy/compat/setup.py" />
        <File name="__init__" src="libs/numpy/core/__init__.py" />
        <File name="_dummy" src="libs/numpy/core/_dummy.pyd" />
        <File name="_internal" src="libs/numpy/core/_internal.py" />
        <File name="_methods" src="libs/numpy/core/_methods.py" />
        <File name="arrayprint" src="libs/numpy/core/arrayprint.py" />
        <File name="cversions" src="libs/numpy/core/cversions.py" />
        <File name="defchararray" src="libs/numpy/core/defchararray.py" />
        <File name="einsumfunc" src="libs/numpy/core/einsumfunc.py" />
        <File name="fromnumeric" src="libs/numpy/core/fromnumeric.py" />
        <File name="function_base" src="libs/numpy/core/function_base.py" />
        <File name="generate_numpy_api" src="libs/numpy/core/generate_numpy_api.py" />
        <File name="getlimits" src="libs/numpy/core/getlimits.py" />
        <File name="info" src="libs/numpy/core/info.py" />
        <File name="machar" src="libs/numpy/core/machar.py" />
        <File name="memmap" src="libs/numpy/core/memmap.py" />
        <File name="multiarray" src="libs/numpy/core/multiarray.pyd" />
        <File name="multiarray_tests" src="libs/numpy/core/multiarray_tests.pyd" />
        <File name="numeric" src="libs/numpy/core/numeric.py" />
        <File name="numerictypes" src="libs/numpy/core/numerictypes.py" />
        <File name="operand_flag_tests" src="libs/numpy/core/operand_flag_tests.pyd" />
        <File name="records" src="libs/numpy/core/records.py" />
        <File name="setup" src="libs/numpy/core/setup.py" />
        <File name="setup_common" src="libs/numpy/core/setup_common.py" />
        <File name="shape_base" src="libs/numpy/core/shape_base.py" />
        <File name="struct_ufunc_test" src="libs/numpy/core/struct_ufunc_test.pyd" />
        <File name="test_rational" src="libs/numpy/core/test_rational.pyd" />
        <File name="umath" src="libs/numpy/core/umath.pyd" />
        <File name="umath_tests" src="libs/numpy/core/umath_tests.pyd" />
        <File name="__multiarray_api" src="libs/numpy/core/include/numpy/__multiarray_api.h" />
        <File name="__ufunc_api" src="libs/numpy/core/include/numpy/__ufunc_api.h" />
        <File name="_neighborhood_iterator_imp" src="libs/numpy/core/include/numpy/_neighborhood_iterator_imp.h" />
        <File name="_numpyconfig" src="libs/numpy/core/include/numpy/_numpyconfig.h" />
        <File name="arrayobject" src="libs/numpy/core/include/numpy/arrayobject.h" />
        <File name="arrayscalars" src="libs/numpy/core/include/numpy/arrayscalars.h" />
        <File name="halffloat" src="libs/numpy/core/include/numpy/halffloat.h" />
        <File name="multiarray_api" src="libs/numpy/core/include/numpy/multiarray_api.txt" />
        <File name="ndarrayobject" src="libs/numpy/core/include/numpy/ndarrayobject.h" />
        <File name="ndarraytypes" src="libs/numpy/core/include/numpy/ndarraytypes.h" />
        <File name="noprefix" src="libs/numpy/core/include/numpy/noprefix.h" />
        <File name="npy_1_7_deprecated_api" src="libs/numpy/core/include/numpy/npy_1_7_deprecated_api.h" />
        <File name="npy_3kcompat" src="libs/numpy/core/include/numpy/npy_3kcompat.h" />
        <File name="npy_common" src="libs/numpy/core/include/numpy/npy_common.h" />
        <File name="npy_cpu" src="libs/numpy/core/include/numpy/npy_cpu.h" />
        <File name="npy_endian" src="libs/numpy/core/include/numpy/npy_endian.h" />
        <File name="npy_interrupt" src="libs/numpy/core/include/numpy/npy_interrupt.h" />
        <File name="npy_math" src="libs/numpy/core/include/numpy/npy_math.h" />
        <File name="npy_no_deprecated_api" src="libs/numpy/core/include/numpy/npy_no_deprecated_api.h" />
        <File name="npy_os" src="libs/numpy/core/include/numpy/npy_os.h" />
        <File name="numpyconfig" src="libs/numpy/core/include/numpy/numpyconfig.h" />
        <File name="old_defines" src="libs/numpy/core/include/numpy/old_defines.h" />
        <File name="oldnumeric" src="libs/numpy/core/include/numpy/oldnumeric.h" />
        <File name="ufunc_api" src="libs/numpy/core/include/numpy/ufunc_api.txt" />
        <File name="ufuncobject" src="libs/numpy/core/include/numpy/ufuncobject.h" />
        <File name="utils" src="libs/numpy/core/include/numpy/utils.h" />
        <File name="npymath" src="libs/numpy/core/lib/npymath.lib" />
        <File name="mlib" src="libs/numpy/core/lib/npy-pkg-config/mlib.ini" />
        <File name="npymath" src="libs/numpy/core/lib/npy-pkg-config/npymath.ini" />
        <File name="__init__" src="libs/numpy/core/tests/__init__.py" />
        <File name="test_abc" src="libs/numpy/core/tests/test_abc.py" />
        <File name="test_api" src="libs/numpy/core/tests/test_api.py" />
        <File name="test_arrayprint" src="libs/numpy/core/tests/test_arrayprint.py" />
        <File name="test_datetime" src="libs/numpy/core/tests/test_datetime.py" />
        <File name="test_defchararray" src="libs/numpy/core/tests/test_defchararray.py" />
        <File name="test_deprecations" src="libs/numpy/core/tests/test_deprecations.py" />
        <File name="test_dtype" src="libs/numpy/core/tests/test_dtype.py" />
        <File name="test_einsum" src="libs/numpy/core/tests/test_einsum.py" />
        <File name="test_errstate" src="libs/numpy/core/tests/test_errstate.py" />
        <File name="test_extint128" src="libs/numpy/core/tests/test_extint128.py" />
        <File name="test_function_base" src="libs/numpy/core/tests/test_function_base.py" />
        <File name="test_getlimits" src="libs/numpy/core/tests/test_getlimits.py" />
        <File name="test_half" src="libs/numpy/core/tests/test_half.py" />
        <File name="test_indexerrors" src="libs/numpy/core/tests/test_indexerrors.py" />
        <File name="test_indexing" src="libs/numpy/core/tests/test_indexing.py" />
        <File name="test_item_selection" src="libs/numpy/core/tests/test_item_selection.py" />
        <File name="test_longdouble" src="libs/numpy/core/tests/test_longdouble.py" />
        <File name="test_machar" src="libs/numpy/core/tests/test_machar.py" />
        <File name="test_mem_overlap" src="libs/numpy/core/tests/test_mem_overlap.py" />
        <File name="test_memmap" src="libs/numpy/core/tests/test_memmap.py" />
        <File name="test_multiarray" src="libs/numpy/core/tests/test_multiarray.py" />
        <File name="test_nditer" src="libs/numpy/core/tests/test_nditer.py" />
        <File name="test_numeric" src="libs/numpy/core/tests/test_numeric.py" />
        <File name="test_numerictypes" src="libs/numpy/core/tests/test_numerictypes.py" />
        <File name="test_print" src="libs/numpy/core/tests/test_print.py" />
        <File name="test_records" src="libs/numpy/core/tests/test_records.py" />
        <File name="test_regression" src="libs/numpy/core/tests/test_regression.py" />
        <File name="test_scalar_ctors" src="libs/numpy/core/tests/test_scalar_ctors.py" />
        <File name="test_scalarinherit" src="libs/numpy/core/tests/test_scalarinherit.py" />
        <File name="test_scalarmath" src="libs/numpy/core/tests/test_scalarmath.py" />
        <File name="test_scalarprint" src="libs/numpy/core/tests/test_scalarprint.py" />
        <File name="test_shape_base" src="libs/numpy/core/tests/test_shape_base.py" />
        <File name="test_ufunc" src="libs/numpy/core/tests/test_ufunc.py" />
        <File name="test_umath" src="libs/numpy/core/tests/test_umath.py" />
        <File name="test_umath_complex" src="libs/numpy/core/tests/test_umath_complex.py" />
        <File name="test_unicode" src="libs/numpy/core/tests/test_unicode.py" />
        <File name="astype_copy" src="libs/numpy/core/tests/data/astype_copy.pkl" />
        <File name="recarray_from_file" src="libs/numpy/core/tests/data/recarray_from_file.fits" />
        <File name="__config__" src="libs/numpy/distutils/__config__.py" />
        <File name="__init__" src="libs/numpy/distutils/__init__.py" />
        <File name="__version__" src="libs/numpy/distutils/__version__.py" />
        <File name="ccompiler" src="libs/numpy/distutils/ccompiler.py" />
        <File name="compat" src="libs/numpy/distutils/compat.py" />
        <File name="conv_template" src="libs/numpy/distutils/conv_template.py" />
        <File name="core" src="libs/numpy/distutils/core.py" />
        <File name="cpuinfo" src="libs/numpy/distutils/cpuinfo.py" />
        <File name="environment" src="libs/numpy/distutils/environment.py" />
        <File name="exec_command" src="libs/numpy/distutils/exec_command.py" />
        <File name="extension" src="libs/numpy/distutils/extension.py" />
        <File name="from_template" src="libs/numpy/distutils/from_template.py" />
        <File name="info" src="libs/numpy/distutils/info.py" />
        <File name="intelccompiler" src="libs/numpy/distutils/intelccompiler.py" />
        <File name="lib2def" src="libs/numpy/distutils/lib2def.py" />
        <File name="line_endings" src="libs/numpy/distutils/line_endings.py" />
        <File name="log" src="libs/numpy/distutils/log.py" />
        <File name="mingw32ccompiler" src="libs/numpy/distutils/mingw32ccompiler.py" />
        <File name="misc_util" src="libs/numpy/distutils/misc_util.py" />
        <File name="msvc9compiler" src="libs/numpy/distutils/msvc9compiler.py" />
        <File name="msvccompiler" src="libs/numpy/distutils/msvccompiler.py" />
        <File name="npy_pkg_config" src="libs/numpy/distutils/npy_pkg_config.py" />
        <File name="numpy_distribution" src="libs/numpy/distutils/numpy_distribution.py" />
        <File name="pathccompiler" src="libs/numpy/distutils/pathccompiler.py" />
        <File name="setup" src="libs/numpy/distutils/setup.py" />
        <File name="system_info" src="libs/numpy/distutils/system_info.py" />
        <File name="unixccompiler" src="libs/numpy/distutils/unixccompiler.py" />
        <File name="__init__" src="libs/numpy/distutils/command/__init__.py" />
        <File name="autodist" src="libs/numpy/distutils/command/autodist.py" />
        <File name="bdist_rpm" src="libs/numpy/distutils/command/bdist_rpm.py" />
        <File name="build" src="libs/numpy/distutils/command/build.py" />
        <File name="build_clib" src="libs/numpy/distutils/command/build_clib.py" />
        <File name="build_ext" src="libs/numpy/distutils/command/build_ext.py" />
        <File name="build_py" src="libs/numpy/distutils/command/build_py.py" />
        <File name="build_scripts" src="libs/numpy/distutils/command/build_scripts.py" />
        <File name="build_src" src="libs/numpy/distutils/command/build_src.py" />
        <File name="config" src="libs/numpy/distutils/command/config.py" />
        <File name="config_compiler" src="libs/numpy/distutils/command/config_compiler.py" />
        <File name="develop" src="libs/numpy/distutils/command/develop.py" />
        <File name="egg_info" src="libs/numpy/distutils/command/egg_info.py" />
        <File name="install" src="libs/numpy/distutils/command/install.py" />
        <File name="install_clib" src="libs/numpy/distutils/command/install_clib.py" />
        <File name="install_data" src="libs/numpy/distutils/command/install_data.py" />
        <File name="install_headers" src="libs/numpy/distutils/command/install_headers.py" />
        <File name="sdist" src="libs/numpy/distutils/command/sdist.py" />
        <File name="__init__" src="libs/numpy/distutils/fcompiler/__init__.py" />
        <File name="absoft" src="libs/numpy/distutils/fcompiler/absoft.py" />
        <File name="compaq" src="libs/numpy/distutils/fcompiler/compaq.py" />
        <File name="g95" src="libs/numpy/distutils/fcompiler/g95.py" />
        <File name="gnu" src="libs/numpy/distutils/fcompiler/gnu.py" />
        <File name="hpux" src="libs/numpy/distutils/fcompiler/hpux.py" />
        <File name="ibm" src="libs/numpy/distutils/fcompiler/ibm.py" />
        <File name="intel" src="libs/numpy/distutils/fcompiler/intel.py" />
        <File name="lahey" src="libs/numpy/distutils/fcompiler/lahey.py" />
        <File name="mips" src="libs/numpy/distutils/fcompiler/mips.py" />
        <File name="nag" src="libs/numpy/distutils/fcompiler/nag.py" />
        <File name="none" src="libs/numpy/distutils/fcompiler/none.py" />
        <File name="pathf95" src="libs/numpy/distutils/fcompiler/pathf95.py" />
        <File name="pg" src="libs/numpy/distutils/fcompiler/pg.py" />
        <File name="sun" src="libs/numpy/distutils/fcompiler/sun.py" />
        <File name="vast" src="libs/numpy/distutils/fcompiler/vast.py" />
        <File name="gfortran_vs2003_hack" src="libs/numpy/distutils/mingw/gfortran_vs2003_hack.c" />
        <File name="__init__" src="libs/numpy/distutils/tests/__init__.py" />
        <File name="test_exec_command" src="libs/numpy/distutils/tests/test_exec_command.py" />
        <File name="test_fcompiler_gnu" src="libs/numpy/distutils/tests/test_fcompiler_gnu.py" />
        <File name="test_fcompiler_intel" src="libs/numpy/distutils/tests/test_fcompiler_intel.py" />
        <File name="test_fcompiler_nagfor" src="libs/numpy/distutils/tests/test_fcompiler_nagfor.py" />
        <File name="test_misc_util" src="libs/numpy/distutils/tests/test_misc_util.py" />
        <File name="test_npy_pkg_config" src="libs/numpy/distutils/tests/test_npy_pkg_config.py" />
        <File name="test_system_info" src="libs/numpy/distutils/tests/test_system_info.py" />
        <File name="__init__" src="libs/numpy/doc/__init__.py" />
        <File name="basics" src="libs/numpy/doc/basics.py" />
        <File name="broadcasting" src="libs/numpy/doc/broadcasting.py" />
        <File name="byteswapping" src="libs/numpy/doc/byteswapping.py" />
        <File name="constants" src="libs/numpy/doc/constants.py" />
        <File name="creation" src="libs/numpy/doc/creation.py" />
        <File name="glossary" src="libs/numpy/doc/glossary.py" />
        <File name="indexing" src="libs/numpy/doc/indexing.py" />
        <File name="internals" src="libs/numpy/doc/internals.py" />
        <File name="misc" src="libs/numpy/doc/misc.py" />
        <File name="structured_arrays" src="libs/numpy/doc/structured_arrays.py" />
        <File name="subclassing" src="libs/numpy/doc/subclassing.py" />
        <File name="ufuncs" src="libs/numpy/doc/ufuncs.py" />
        <File name="__init__" src="libs/numpy/f2py/__init__.py" />
        <File name="__main__" src="libs/numpy/f2py/__main__.py" />
        <File name="__version__" src="libs/numpy/f2py/__version__.py" />
        <File name="auxfuncs" src="libs/numpy/f2py/auxfuncs.py" />
        <File name="capi_maps" src="libs/numpy/f2py/capi_maps.py" />
        <File name="cb_rules" src="libs/numpy/f2py/cb_rules.py" />
        <File name="cfuncs" src="libs/numpy/f2py/cfuncs.py" />
        <File name="common_rules" src="libs/numpy/f2py/common_rules.py" />
        <File name="crackfortran" src="libs/numpy/f2py/crackfortran.py" />
        <File name="diagnose" src="libs/numpy/f2py/diagnose.py" />
        <File name="f2py2e" src="libs/numpy/f2py/f2py2e.py" />
        <File name="f2py_testing" src="libs/numpy/f2py/f2py_testing.py" />
        <File name="f90mod_rules" src="libs/numpy/f2py/f90mod_rules.py" />
        <File name="func2subr" src="libs/numpy/f2py/func2subr.py" />
        <File name="info" src="libs/numpy/f2py/info.py" />
        <File name="rules" src="libs/numpy/f2py/rules.py" />
        <File name="setup" src="libs/numpy/f2py/setup.py" />
        <File name="use_rules" src="libs/numpy/f2py/use_rules.py" />
        <File name="fortranobject" src="libs/numpy/f2py/src/fortranobject.c" />
        <File name="fortranobject" src="libs/numpy/f2py/src/fortranobject.h" />
        <File name="__init__" src="libs/numpy/f2py/tests/__init__.py" />
        <File name="test_array_from_pyobj" src="libs/numpy/f2py/tests/test_array_from_pyobj.py" />
        <File name="test_assumed_shape" src="libs/numpy/f2py/tests/test_assumed_shape.py" />
        <File name="test_block_docstring" src="libs/numpy/f2py/tests/test_block_docstring.py" />
        <File name="test_callback" src="libs/numpy/f2py/tests/test_callback.py" />
        <File name="test_common" src="libs/numpy/f2py/tests/test_common.py" />
        <File name="test_kind" src="libs/numpy/f2py/tests/test_kind.py" />
        <File name="test_mixed" src="libs/numpy/f2py/tests/test_mixed.py" />
        <File name="test_parameter" src="libs/numpy/f2py/tests/test_parameter.py" />
        <File name="test_regression" src="libs/numpy/f2py/tests/test_regression.py" />
        <File name="test_return_character" src="libs/numpy/f2py/tests/test_return_character.py" />
        <File name="test_return_complex" src="libs/numpy/f2py/tests/test_return_complex.py" />
        <File name="test_return_integer" src="libs/numpy/f2py/tests/test_return_integer.py" />
        <File name="test_return_logical" src="libs/numpy/f2py/tests/test_return_logical.py" />
        <File name="test_return_real" src="libs/numpy/f2py/tests/test_return_real.py" />
        <File name="test_size" src="libs/numpy/f2py/tests/test_size.py" />
        <File name="test_string" src="libs/numpy/f2py/tests/test_string.py" />
        <File name="util" src="libs/numpy/f2py/tests/util.py" />
        <File name="wrapmodule" src="libs/numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c" />
        <File name="" src="libs/numpy/f2py/tests/src/assumed_shape/.f2py_f2cmap" />
        <File name="foo_free" src="libs/numpy/f2py/tests/src/assumed_shape/foo_free.f90" />
        <File name="foo_mod" src="libs/numpy/f2py/tests/src/assumed_shape/foo_mod.f90" />
        <File name="foo_use" src="libs/numpy/f2py/tests/src/assumed_shape/foo_use.f90" />
        <File name="precision" src="libs/numpy/f2py/tests/src/assumed_shape/precision.f90" />
        <File name="block" src="libs/numpy/f2py/tests/src/common/block.f" />
        <File name="foo" src="libs/numpy/f2py/tests/src/kind/foo.f90" />
        <File name="foo" src="libs/numpy/f2py/tests/src/mixed/foo.f" />
        <File name="foo_fixed" src="libs/numpy/f2py/tests/src/mixed/foo_fixed.f90" />
        <File name="foo_free" src="libs/numpy/f2py/tests/src/mixed/foo_free.f90" />
        <File name="constant_both" src="libs/numpy/f2py/tests/src/parameter/constant_both.f90" />
        <File name="constant_compound" src="libs/numpy/f2py/tests/src/parameter/constant_compound.f90" />
        <File name="constant_integer" src="libs/numpy/f2py/tests/src/parameter/constant_integer.f90" />
        <File name="constant_non_compound" src="libs/numpy/f2py/tests/src/parameter/constant_non_compound.f90" />
        <File name="constant_real" src="libs/numpy/f2py/tests/src/parameter/constant_real.f90" />
        <File name="inout" src="libs/numpy/f2py/tests/src/regression/inout.f90" />
        <File name="foo" src="libs/numpy/f2py/tests/src/size/foo.f90" />
        <File name="char" src="libs/numpy/f2py/tests/src/string/char.f90" />
        <File name="__init__" src="libs/numpy/fft/__init__.py" />
        <File name="fftpack" src="libs/numpy/fft/fftpack.py" />
        <File name="fftpack_lite" src="libs/numpy/fft/fftpack_lite.pyd" />
        <File name="helper" src="libs/numpy/fft/helper.py" />
        <File name="info" src="libs/numpy/fft/info.py" />
        <File name="setup" src="libs/numpy/fft/setup.py" />
        <File name="__init__" src="libs/numpy/fft/tests/__init__.py" />
        <File name="test_fftpack" src="libs/numpy/fft/tests/test_fftpack.py" />
        <File name="test_helper" src="libs/numpy/fft/tests/test_helper.py" />
        <File name="__init__" src="libs/numpy/lib/__init__.py" />
        <File name="_datasource" src="libs/numpy/lib/_datasource.py" />
        <File name="_iotools" src="libs/numpy/lib/_iotools.py" />
        <File name="_version" src="libs/numpy/lib/_version.py" />
        <File name="arraypad" src="libs/numpy/lib/arraypad.py" />
        <File name="arraysetops" src="libs/numpy/lib/arraysetops.py" />
        <File name="arrayterator" src="libs/numpy/lib/arrayterator.py" />
        <File name="financial" src="libs/numpy/lib/financial.py" />
        <File name="format" src="libs/numpy/lib/format.py" />
        <File name="function_base" src="libs/numpy/lib/function_base.py" />
        <File name="index_tricks" src="libs/numpy/lib/index_tricks.py" />
        <File name="info" src="libs/numpy/lib/info.py" />
        <File name="mixins" src="libs/numpy/lib/mixins.py" />
        <File name="nanfunctions" src="libs/numpy/lib/nanfunctions.py" />
        <File name="npyio" src="libs/numpy/lib/npyio.py" />
        <File name="polynomial" src="libs/numpy/lib/polynomial.py" />
        <File name="recfunctions" src="libs/numpy/lib/recfunctions.py" />
        <File name="scimath" src="libs/numpy/lib/scimath.py" />
        <File name="setup" src="libs/numpy/lib/setup.py" />
        <File name="shape_base" src="libs/numpy/lib/shape_base.py" />
        <File name="stride_tricks" src="libs/numpy/lib/stride_tricks.py" />
        <File name="twodim_base" src="libs/numpy/lib/twodim_base.py" />
        <File name="type_check" src="libs/numpy/lib/type_check.py" />
        <File name="ufunclike" src="libs/numpy/lib/ufunclike.py" />
        <File name="user_array" src="libs/numpy/lib/user_array.py" />
        <File name="utils" src="libs/numpy/lib/utils.py" />
        <File name="__init__" src="libs/numpy/lib/tests/__init__.py" />
        <File name="test__datasource" src="libs/numpy/lib/tests/test__datasource.py" />
        <File name="test__iotools" src="libs/numpy/lib/tests/test__iotools.py" />
        <File name="test__version" src="libs/numpy/lib/tests/test__version.py" />
        <File name="test_arraypad" src="libs/numpy/lib/tests/test_arraypad.py" />
        <File name="test_arraysetops" src="libs/numpy/lib/tests/test_arraysetops.py" />
        <File name="test_arrayterator" src="libs/numpy/lib/tests/test_arrayterator.py" />
        <File name="test_financial" src="libs/numpy/lib/tests/test_financial.py" />
        <File name="test_format" src="libs/numpy/lib/tests/test_format.py" />
        <File name="test_function_base" src="libs/numpy/lib/tests/test_function_base.py" />
        <File name="test_index_tricks" src="libs/numpy/lib/tests/test_index_tricks.py" />
        <File name="test_io" src="libs/numpy/lib/tests/test_io.py" />
        <File name="test_mixins" src="libs/numpy/lib/tests/test_mixins.py" />
        <File name="test_nanfunctions" src="libs/numpy/lib/tests/test_nanfunctions.py" />
        <File name="test_packbits" src="libs/numpy/lib/tests/test_packbits.py" />
        <File name="test_polynomial" src="libs/numpy/lib/tests/test_polynomial.py" />
        <File name="test_recfunctions" src="libs/numpy/lib/tests/test_recfunctions.py" />
        <File name="test_regression" src="libs/numpy/lib/tests/test_regression.py" />
        <File name="test_shape_base" src="libs/numpy/lib/tests/test_shape_base.py" />
        <File name="test_stride_tricks" src="libs/numpy/lib/tests/test_stride_tricks.py" />
        <File name="test_twodim_base" src="libs/numpy/lib/tests/test_twodim_base.py" />
        <File name="test_type_check" src="libs/numpy/lib/tests/test_type_check.py" />
        <File name="test_ufunclike" src="libs/numpy/lib/tests/test_ufunclike.py" />
        <File name="test_utils" src="libs/numpy/lib/tests/test_utils.py" />
        <File name="py2-objarr" src="libs/numpy/lib/tests/data/py2-objarr.npy" />
        <File name="py2-objarr" src="libs/numpy/lib/tests/data/py2-objarr.npz" />
        <File name="py3-objarr" src="libs/numpy/lib/tests/data/py3-objarr.npy" />
        <File name="py3-objarr" src="libs/numpy/lib/tests/data/py3-objarr.npz" />
        <File name="python3" src="libs/numpy/lib/tests/data/python3.npy" />
        <File name="win64python2" src="libs/numpy/lib/tests/data/win64python2.npy" />
        <File name="__init__" src="libs/numpy/linalg/__init__.py" />
        <File name="_umath_linalg" src="libs/numpy/linalg/_umath_linalg.pyd" />
        <File name="info" src="libs/numpy/linalg/info.py" />
        <File name="lapack_lite" src="libs/numpy/linalg/lapack_lite.pyd" />
        <File name="linalg" src="libs/numpy/linalg/linalg.py" />
        <File name="setup" src="libs/numpy/linalg/setup.py" />
        <File name="__init__" src="libs/numpy/linalg/tests/__init__.py" />
        <File name="test_build" src="libs/numpy/linalg/tests/test_build.py" />
        <File name="test_deprecations" src="libs/numpy/linalg/tests/test_deprecations.py" />
        <File name="test_linalg" src="libs/numpy/linalg/tests/test_linalg.py" />
        <File name="test_regression" src="libs/numpy/linalg/tests/test_regression.py" />
        <File name="__init__" src="libs/numpy/ma/__init__.py" />
        <File name="bench" src="libs/numpy/ma/bench.py" />
        <File name="core" src="libs/numpy/ma/core.py" />
        <File name="extras" src="libs/numpy/ma/extras.py" />
        <File name="mrecords" src="libs/numpy/ma/mrecords.py" />
        <File name="setup" src="libs/numpy/ma/setup.py" />
        <File name="testutils" src="libs/numpy/ma/testutils.py" />
        <File name="timer_comparison" src="libs/numpy/ma/timer_comparison.py" />
        <File name="version" src="libs/numpy/ma/version.py" />
        <File name="__init__" src="libs/numpy/ma/tests/__init__.py" />
        <File name="test_core" src="libs/numpy/ma/tests/test_core.py" />
        <File name="test_deprecations" src="libs/numpy/ma/tests/test_deprecations.py" />
        <File name="test_extras" src="libs/numpy/ma/tests/test_extras.py" />
        <File name="test_mrecords" src="libs/numpy/ma/tests/test_mrecords.py" />
        <File name="test_old_ma" src="libs/numpy/ma/tests/test_old_ma.py" />
        <File name="test_regression" src="libs/numpy/ma/tests/test_regression.py" />
        <File name="test_subclassing" src="libs/numpy/ma/tests/test_subclassing.py" />
        <File name="__init__" src="libs/numpy/matrixlib/__init__.py" />
        <File name="defmatrix" src="libs/numpy/matrixlib/defmatrix.py" />
        <File name="setup" src="libs/numpy/matrixlib/setup.py" />
        <File name="__init__" src="libs/numpy/matrixlib/tests/__init__.py" />
        <File name="test_defmatrix" src="libs/numpy/matrixlib/tests/test_defmatrix.py" />
        <File name="test_multiarray" src="libs/numpy/matrixlib/tests/test_multiarray.py" />
        <File name="test_numeric" src="libs/numpy/matrixlib/tests/test_numeric.py" />
        <File name="test_regression" src="libs/numpy/matrixlib/tests/test_regression.py" />
        <File name="__init__" src="libs/numpy/polynomial/__init__.py" />
        <File name="_polybase" src="libs/numpy/polynomial/_polybase.py" />
        <File name="chebyshev" src="libs/numpy/polynomial/chebyshev.py" />
        <File name="hermite" src="libs/numpy/polynomial/hermite.py" />
        <File name="hermite_e" src="libs/numpy/polynomial/hermite_e.py" />
        <File name="laguerre" src="libs/numpy/polynomial/laguerre.py" />
        <File name="legendre" src="libs/numpy/polynomial/legendre.py" />
        <File name="polynomial" src="libs/numpy/polynomial/polynomial.py" />
        <File name="polyutils" src="libs/numpy/polynomial/polyutils.py" />
        <File name="setup" src="libs/numpy/polynomial/setup.py" />
        <File name="__init__" src="libs/numpy/polynomial/tests/__init__.py" />
        <File name="test_chebyshev" src="libs/numpy/polynomial/tests/test_chebyshev.py" />
        <File name="test_classes" src="libs/numpy/polynomial/tests/test_classes.py" />
        <File name="test_hermite" src="libs/numpy/polynomial/tests/test_hermite.py" />
        <File name="test_hermite_e" src="libs/numpy/polynomial/tests/test_hermite_e.py" />
        <File name="test_laguerre" src="libs/numpy/polynomial/tests/test_laguerre.py" />
        <File name="test_legendre" src="libs/numpy/polynomial/tests/test_legendre.py" />
        <File name="test_polynomial" src="libs/numpy/polynomial/tests/test_polynomial.py" />
        <File name="test_polyutils" src="libs/numpy/polynomial/tests/test_polyutils.py" />
        <File name="test_printing" src="libs/numpy/polynomial/tests/test_printing.py" />
        <File name="__init__" src="libs/numpy/random/__init__.py" />
        <File name="info" src="libs/numpy/random/info.py" />
        <File name="mtrand" src="libs/numpy/random/mtrand.pyd" />
        <File name="randomkit" src="libs/numpy/random/randomkit.h" />
        <File name="setup" src="libs/numpy/random/setup.py" />
        <File name="__init__" src="libs/numpy/random/tests/__init__.py" />
        <File name="test_random" src="libs/numpy/random/tests/test_random.py" />
        <File name="test_regression" src="libs/numpy/random/tests/test_regression.py" />
        <File name="__init__" src="libs/numpy/testing/__init__.py" />
        <File name="decorators" src="libs/numpy/testing/decorators.py" />
        <File name="noseclasses" src="libs/numpy/testing/noseclasses.py" />
        <File name="nosetester" src="libs/numpy/testing/nosetester.py" />
        <File name="print_coercion_tables" src="libs/numpy/testing/print_coercion_tables.py" />
        <File name="setup" src="libs/numpy/testing/setup.py" />
        <File name="utils" src="libs/numpy/testing/utils.py" />
        <File name="__init__" src="libs/numpy/testing/nose_tools/__init__.py" />
        <File name="decorators" src="libs/numpy/testing/nose_tools/decorators.py" />
        <File name="noseclasses" src="libs/numpy/testing/nose_tools/noseclasses.py" />
        <File name="nosetester" src="libs/numpy/testing/nose_tools/nosetester.py" />
        <File name="parameterized" src="libs/numpy/testing/nose_tools/parameterized.py" />
        <File name="utils" src="libs/numpy/testing/nose_tools/utils.py" />
        <File name="__init__" src="libs/numpy/testing/tests/__init__.py" />
        <File name="test_decorators" src="libs/numpy/testing/tests/test_decorators.py" />
        <File name="test_doctesting" src="libs/numpy/testing/tests/test_doctesting.py" />
        <File name="test_utils" src="libs/numpy/testing/tests/test_utils.py" />
        <File name="__init__" src="libs/numpy/tests/__init__.py" />
        <File name="test_ctypeslib" src="libs/numpy/tests/test_ctypeslib.py" />
        <File name="test_matlib" src="libs/numpy/tests/test_matlib.py" />
        <File name="test_numpy_version" src="libs/numpy/tests/test_numpy_version.py" />
        <File name="test_reloading" src="libs/numpy/tests/test_reloading.py" />
        <File name="test_scripts" src="libs/numpy/tests/test_scripts.py" />
        <File name="test_warnings" src="libs/numpy/tests/test_warnings.py" />
        <File name="DESCRIPTION" src="libs/numpy-1.14.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/numpy-1.14.4.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/numpy-1.14.4.dist-info/METADATA" />
        <File name="metadata" src="libs/numpy-1.14.4.dist-info/metadata.json" />
        <File name="RECORD" src="libs/numpy-1.14.4.dist-info/RECORD" />
        <File name="top_level" src="libs/numpy-1.14.4.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/numpy-1.14.4.dist-info/WHEEL" />
        <File name="__init__" src="libs/oauth2client/__init__.py" />
        <File name="_helpers" src="libs/oauth2client/_helpers.py" />
        <File name="_openssl_crypt" src="libs/oauth2client/_openssl_crypt.py" />
        <File name="_pkce" src="libs/oauth2client/_pkce.py" />
        <File name="_pure_python_crypt" src="libs/oauth2client/_pure_python_crypt.py" />
        <File name="_pycrypto_crypt" src="libs/oauth2client/_pycrypto_crypt.py" />
        <File name="client" src="libs/oauth2client/client.py" />
        <File name="clientsecrets" src="libs/oauth2client/clientsecrets.py" />
        <File name="crypt" src="libs/oauth2client/crypt.py" />
        <File name="file" src="libs/oauth2client/file.py" />
        <File name="service_account" src="libs/oauth2client/service_account.py" />
        <File name="tools" src="libs/oauth2client/tools.py" />
        <File name="transport" src="libs/oauth2client/transport.py" />
        <File name="__init__" src="libs/oauth2client/contrib/__init__.py" />
        <File name="_appengine_ndb" src="libs/oauth2client/contrib/_appengine_ndb.py" />
        <File name="_metadata" src="libs/oauth2client/contrib/_metadata.py" />
        <File name="appengine" src="libs/oauth2client/contrib/appengine.py" />
        <File name="devshell" src="libs/oauth2client/contrib/devshell.py" />
        <File name="dictionary_storage" src="libs/oauth2client/contrib/dictionary_storage.py" />
        <File name="flask_util" src="libs/oauth2client/contrib/flask_util.py" />
        <File name="gce" src="libs/oauth2client/contrib/gce.py" />
        <File name="keyring_storage" src="libs/oauth2client/contrib/keyring_storage.py" />
        <File name="multiprocess_file_storage" src="libs/oauth2client/contrib/multiprocess_file_storage.py" />
        <File name="sqlalchemy" src="libs/oauth2client/contrib/sqlalchemy.py" />
        <File name="xsrfutil" src="libs/oauth2client/contrib/xsrfutil.py" />
        <File name="__init__" src="libs/oauth2client/contrib/django_util/__init__.py" />
        <File name="apps" src="libs/oauth2client/contrib/django_util/apps.py" />
        <File name="decorators" src="libs/oauth2client/contrib/django_util/decorators.py" />
        <File name="models" src="libs/oauth2client/contrib/django_util/models.py" />
        <File name="signals" src="libs/oauth2client/contrib/django_util/signals.py" />
        <File name="site" src="libs/oauth2client/contrib/django_util/site.py" />
        <File name="storage" src="libs/oauth2client/contrib/django_util/storage.py" />
        <File name="views" src="libs/oauth2client/contrib/django_util/views.py" />
        <File name="DESCRIPTION" src="libs/oauth2client-4.1.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/oauth2client-4.1.2.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/oauth2client-4.1.2.dist-info/METADATA" />
        <File name="metadata" src="libs/oauth2client-4.1.2.dist-info/metadata.json" />
        <File name="RECORD" src="libs/oauth2client-4.1.2.dist-info/RECORD" />
        <File name="top_level" src="libs/oauth2client-4.1.2.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/oauth2client-4.1.2.dist-info/WHEEL" />
        <File name="__init__" src="libs/pyasn1/__init__.py" />
        <File name="debug" src="libs/pyasn1/debug.py" />
        <File name="error" src="libs/pyasn1/error.py" />
        <File name="__init__" src="libs/pyasn1/codec/__init__.py" />
        <File name="__init__" src="libs/pyasn1/codec/ber/__init__.py" />
        <File name="decoder" src="libs/pyasn1/codec/ber/decoder.py" />
        <File name="encoder" src="libs/pyasn1/codec/ber/encoder.py" />
        <File name="eoo" src="libs/pyasn1/codec/ber/eoo.py" />
        <File name="__init__" src="libs/pyasn1/codec/cer/__init__.py" />
        <File name="decoder" src="libs/pyasn1/codec/cer/decoder.py" />
        <File name="encoder" src="libs/pyasn1/codec/cer/encoder.py" />
        <File name="__init__" src="libs/pyasn1/codec/der/__init__.py" />
        <File name="decoder" src="libs/pyasn1/codec/der/decoder.py" />
        <File name="encoder" src="libs/pyasn1/codec/der/encoder.py" />
        <File name="__init__" src="libs/pyasn1/codec/native/__init__.py" />
        <File name="decoder" src="libs/pyasn1/codec/native/decoder.py" />
        <File name="encoder" src="libs/pyasn1/codec/native/encoder.py" />
        <File name="__init__" src="libs/pyasn1/compat/__init__.py" />
        <File name="binary" src="libs/pyasn1/compat/binary.py" />
        <File name="calling" src="libs/pyasn1/compat/calling.py" />
        <File name="dateandtime" src="libs/pyasn1/compat/dateandtime.py" />
        <File name="integer" src="libs/pyasn1/compat/integer.py" />
        <File name="octets" src="libs/pyasn1/compat/octets.py" />
        <File name="string" src="libs/pyasn1/compat/string.py" />
        <File name="__init__" src="libs/pyasn1/type/__init__.py" />
        <File name="base" src="libs/pyasn1/type/base.py" />
        <File name="char" src="libs/pyasn1/type/char.py" />
        <File name="constraint" src="libs/pyasn1/type/constraint.py" />
        <File name="error" src="libs/pyasn1/type/error.py" />
        <File name="namedtype" src="libs/pyasn1/type/namedtype.py" />
        <File name="namedval" src="libs/pyasn1/type/namedval.py" />
        <File name="opentype" src="libs/pyasn1/type/opentype.py" />
        <File name="tag" src="libs/pyasn1/type/tag.py" />
        <File name="tagmap" src="libs/pyasn1/type/tagmap.py" />
        <File name="univ" src="libs/pyasn1/type/univ.py" />
        <File name="useful" src="libs/pyasn1/type/useful.py" />
        <File name="DESCRIPTION" src="libs/pyasn1-0.4.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/pyasn1-0.4.2.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/pyasn1-0.4.2.dist-info/METADATA" />
        <File name="metadata" src="libs/pyasn1-0.4.2.dist-info/metadata.json" />
        <File name="RECORD" src="libs/pyasn1-0.4.2.dist-info/RECORD" />
        <File name="top_level" src="libs/pyasn1-0.4.2.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/pyasn1-0.4.2.dist-info/WHEEL" />
        <File name="zip-safe" src="libs/pyasn1-0.4.2.dist-info/zip-safe" />
        <File name="__init__" src="libs/pyasn1_modules/__init__.py" />
        <File name="pem" src="libs/pyasn1_modules/pem.py" />
        <File name="rfc1155" src="libs/pyasn1_modules/rfc1155.py" />
        <File name="rfc1157" src="libs/pyasn1_modules/rfc1157.py" />
        <File name="rfc1901" src="libs/pyasn1_modules/rfc1901.py" />
        <File name="rfc1902" src="libs/pyasn1_modules/rfc1902.py" />
        <File name="rfc1905" src="libs/pyasn1_modules/rfc1905.py" />
        <File name="rfc2251" src="libs/pyasn1_modules/rfc2251.py" />
        <File name="rfc2314" src="libs/pyasn1_modules/rfc2314.py" />
        <File name="rfc2315" src="libs/pyasn1_modules/rfc2315.py" />
        <File name="rfc2437" src="libs/pyasn1_modules/rfc2437.py" />
        <File name="rfc2459" src="libs/pyasn1_modules/rfc2459.py" />
        <File name="rfc2511" src="libs/pyasn1_modules/rfc2511.py" />
        <File name="rfc2560" src="libs/pyasn1_modules/rfc2560.py" />
        <File name="rfc3279" src="libs/pyasn1_modules/rfc3279.py" />
        <File name="rfc3280" src="libs/pyasn1_modules/rfc3280.py" />
        <File name="rfc3281" src="libs/pyasn1_modules/rfc3281.py" />
        <File name="rfc3412" src="libs/pyasn1_modules/rfc3412.py" />
        <File name="rfc3414" src="libs/pyasn1_modules/rfc3414.py" />
        <File name="rfc3447" src="libs/pyasn1_modules/rfc3447.py" />
        <File name="rfc3852" src="libs/pyasn1_modules/rfc3852.py" />
        <File name="rfc4210" src="libs/pyasn1_modules/rfc4210.py" />
        <File name="rfc4211" src="libs/pyasn1_modules/rfc4211.py" />
        <File name="rfc5208" src="libs/pyasn1_modules/rfc5208.py" />
        <File name="rfc5280" src="libs/pyasn1_modules/rfc5280.py" />
        <File name="rfc5652" src="libs/pyasn1_modules/rfc5652.py" />
        <File name="rfc6402" src="libs/pyasn1_modules/rfc6402.py" />
        <File name="DESCRIPTION" src="libs/pyasn1_modules-0.2.1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/pyasn1_modules-0.2.1.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/pyasn1_modules-0.2.1.dist-info/METADATA" />
        <File name="metadata" src="libs/pyasn1_modules-0.2.1.dist-info/metadata.json" />
        <File name="RECORD" src="libs/pyasn1_modules-0.2.1.dist-info/RECORD" />
        <File name="top_level" src="libs/pyasn1_modules-0.2.1.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/pyasn1_modules-0.2.1.dist-info/WHEEL" />
        <File name="zip-safe" src="libs/pyasn1_modules-0.2.1.dist-info/zip-safe" />
        <File name="__init__" src="libs/rsa/__init__.py" />
        <File name="_compat" src="libs/rsa/_compat.py" />
        <File name="_version133" src="libs/rsa/_version133.py" />
        <File name="_version200" src="libs/rsa/_version200.py" />
        <File name="asn1" src="libs/rsa/asn1.py" />
        <File name="bigfile" src="libs/rsa/bigfile.py" />
        <File name="cli" src="libs/rsa/cli.py" />
        <File name="common" src="libs/rsa/common.py" />
        <File name="core" src="libs/rsa/core.py" />
        <File name="key" src="libs/rsa/key.py" />
        <File name="parallel" src="libs/rsa/parallel.py" />
        <File name="pem" src="libs/rsa/pem.py" />
        <File name="pkcs1" src="libs/rsa/pkcs1.py" />
        <File name="prime" src="libs/rsa/prime.py" />
        <File name="randnum" src="libs/rsa/randnum.py" />
        <File name="transform" src="libs/rsa/transform.py" />
        <File name="util" src="libs/rsa/util.py" />
        <File name="varblock" src="libs/rsa/varblock.py" />
        <File name="DESCRIPTION" src="libs/rsa-3.4.2.dist-info/DESCRIPTION.rst" />
        <File name="entry_points" src="libs/rsa-3.4.2.dist-info/entry_points.txt" />
        <File name="INSTALLER" src="libs/rsa-3.4.2.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/rsa-3.4.2.dist-info/METADATA" />
        <File name="metadata" src="libs/rsa-3.4.2.dist-info/metadata.json" />
        <File name="RECORD" src="libs/rsa-3.4.2.dist-info/RECORD" />
        <File name="top_level" src="libs/rsa-3.4.2.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/rsa-3.4.2.dist-info/WHEEL" />
        <File name="DESCRIPTION" src="libs/six-1.11.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/six-1.11.0.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/six-1.11.0.dist-info/METADATA" />
        <File name="metadata" src="libs/six-1.11.0.dist-info/metadata.json" />
        <File name="RECORD" src="libs/six-1.11.0.dist-info/RECORD" />
        <File name="top_level" src="libs/six-1.11.0.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/six-1.11.0.dist-info/WHEEL" />
        <File name="__init__" src="libs/uritemplate/__init__.py" />
        <File name="api" src="libs/uritemplate/api.py" />
        <File name="template" src="libs/uritemplate/template.py" />
        <File name="variable" src="libs/uritemplate/variable.py" />
        <File name="DESCRIPTION" src="libs/uritemplate-3.0.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/uritemplate-3.0.0.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/uritemplate-3.0.0.dist-info/METADATA" />
        <File name="metadata" src="libs/uritemplate-3.0.0.dist-info/metadata.json" />
        <File name="RECORD" src="libs/uritemplate-3.0.0.dist-info/RECORD" />
        <File name="top_level" src="libs/uritemplate-3.0.0.dist-info/top_level.txt" />
        <File name="WHEEL" src="libs/uritemplate-3.0.0.dist-info/WHEEL" />
        <File name="translation_ja_JP" src="translations/translation_ja_JP.qm" />
    </Resources>
    <Topics>
        <Topic name="interaction_jpj" src="dialog/interaction/interaction_jpj.top" topicName="interaction" language="ja_JP" />
    </Topics>
    <IgnoredPaths />
    <Translations auto-fill="ja_JP">
        <Translation name="translation_ja_JP" src="translations/translation_ja_JP.ts" language="ja_JP" />
    </Translations>
</Package>
