<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Sample" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="." xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="interaction" src="dialog/interaction/interaction.dlg" />
    </Dialogs>
    <Resources>
        <File name="app" src="html/css/app.css" />
        <File name="default" src="html/css/default.css" />
        <File name="reset" src="html/css/reset.css" />
        <File name="index" src="html/index.html" />
        <File name="Sample" src="Sample.phpproj" />
        <File name="adjust" src="html/js/adjust.js" />
        <File name="se_quiz_failure" src="html/audio/se_quiz_failure.ogg" />
        <File name="se_quiz_start" src="html/audio/se_quiz_start.ogg" />
        <File name="se_quiz_success" src="html/audio/se_quiz_success.ogg" />
        <File name="bgm" src="html/audio/bgm.ogg" />
        <File name="app" src="app.cnf" />
        <File name="Sample" src="Sample.sln" />
        <File name="contents" src="html/js/contents.js" />
        <File name="tapper" src="html/js/tapper.js" />
        <File name="tapper_audio" src="html/js/tapper_audio.js" />
        <File name="bg_common" src="html/images/preloads/bg_common.png" />
        <File name="bg_splash" src="html/images/preloads/bg_splash.png" />
        <File name="text_correct" src="html/images/preloads/text_correct.png" />
        <File name="text_incorrect" src="html/images/preloads/text_incorrect.png" />
        <File name="se_btn_touched" src="html/audio/se_btn_touched.ogg" />
        <File name="tapper_preview" src="html/js/tapper_preview.js" />
        <File name="se_recognize_end" src="html/audio/se_recognize_end.ogg" />
        <File name="se_recognize_start" src="html/audio/se_recognize_start.ogg" />
        <File name="__init__" src="libs/backports/__init__.py" />
        <File name="LICENSE" src="libs/backports/ssl_match_hostname/LICENSE.txt" />
        <File name="README" src="libs/backports/ssl_match_hostname/README.txt" />
        <File name="__init__" src="libs/backports/ssl_match_hostname/__init__.py" />
        <File name="DESCRIPTION" src="libs/certifi-2017.7.27.1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/certifi-2017.7.27.1.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/certifi-2017.7.27.1.dist-info/METADATA" />
        <File name="RECORD" src="libs/certifi-2017.7.27.1.dist-info/RECORD" />
        <File name="WHEEL" src="libs/certifi-2017.7.27.1.dist-info/WHEEL" />
        <File name="metadata" src="libs/certifi-2017.7.27.1.dist-info/metadata.json" />
        <File name="top_level" src="libs/certifi-2017.7.27.1.dist-info/top_level.txt" />
        <File name="__init__" src="libs/certifi/__init__.py" />
        <File name="__main__" src="libs/certifi/__main__.py" />
        <File name="cacert" src="libs/certifi/cacert.pem" />
        <File name="core" src="libs/certifi/core.py" />
        <File name="old_root" src="libs/certifi/old_root.pem" />
        <File name="weak" src="libs/certifi/weak.pem" />
        <File name="DESCRIPTION" src="libs/chardet-3.0.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/chardet-3.0.4.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/chardet-3.0.4.dist-info/METADATA" />
        <File name="RECORD" src="libs/chardet-3.0.4.dist-info/RECORD" />
        <File name="WHEEL" src="libs/chardet-3.0.4.dist-info/WHEEL" />
        <File name="entry_points" src="libs/chardet-3.0.4.dist-info/entry_points.txt" />
        <File name="metadata" src="libs/chardet-3.0.4.dist-info/metadata.json" />
        <File name="top_level" src="libs/chardet-3.0.4.dist-info/top_level.txt" />
        <File name="__init__" src="libs/chardet/__init__.py" />
        <File name="big5freq" src="libs/chardet/big5freq.py" />
        <File name="big5prober" src="libs/chardet/big5prober.py" />
        <File name="chardistribution" src="libs/chardet/chardistribution.py" />
        <File name="charsetgroupprober" src="libs/chardet/charsetgroupprober.py" />
        <File name="charsetprober" src="libs/chardet/charsetprober.py" />
        <File name="__init__" src="libs/chardet/cli/__init__.py" />
        <File name="chardetect" src="libs/chardet/cli/chardetect.py" />
        <File name="codingstatemachine" src="libs/chardet/codingstatemachine.py" />
        <File name="compat" src="libs/chardet/compat.py" />
        <File name="cp949prober" src="libs/chardet/cp949prober.py" />
        <File name="enums" src="libs/chardet/enums.py" />
        <File name="escprober" src="libs/chardet/escprober.py" />
        <File name="escsm" src="libs/chardet/escsm.py" />
        <File name="eucjpprober" src="libs/chardet/eucjpprober.py" />
        <File name="euckrfreq" src="libs/chardet/euckrfreq.py" />
        <File name="euckrprober" src="libs/chardet/euckrprober.py" />
        <File name="euctwfreq" src="libs/chardet/euctwfreq.py" />
        <File name="euctwprober" src="libs/chardet/euctwprober.py" />
        <File name="gb2312freq" src="libs/chardet/gb2312freq.py" />
        <File name="gb2312prober" src="libs/chardet/gb2312prober.py" />
        <File name="hebrewprober" src="libs/chardet/hebrewprober.py" />
        <File name="jisfreq" src="libs/chardet/jisfreq.py" />
        <File name="jpcntx" src="libs/chardet/jpcntx.py" />
        <File name="langbulgarianmodel" src="libs/chardet/langbulgarianmodel.py" />
        <File name="langcyrillicmodel" src="libs/chardet/langcyrillicmodel.py" />
        <File name="langgreekmodel" src="libs/chardet/langgreekmodel.py" />
        <File name="langhebrewmodel" src="libs/chardet/langhebrewmodel.py" />
        <File name="langhungarianmodel" src="libs/chardet/langhungarianmodel.py" />
        <File name="langthaimodel" src="libs/chardet/langthaimodel.py" />
        <File name="langturkishmodel" src="libs/chardet/langturkishmodel.py" />
        <File name="latin1prober" src="libs/chardet/latin1prober.py" />
        <File name="mbcharsetprober" src="libs/chardet/mbcharsetprober.py" />
        <File name="mbcsgroupprober" src="libs/chardet/mbcsgroupprober.py" />
        <File name="mbcssm" src="libs/chardet/mbcssm.py" />
        <File name="sbcharsetprober" src="libs/chardet/sbcharsetprober.py" />
        <File name="sbcsgroupprober" src="libs/chardet/sbcsgroupprober.py" />
        <File name="sjisprober" src="libs/chardet/sjisprober.py" />
        <File name="universaldetector" src="libs/chardet/universaldetector.py" />
        <File name="utf8prober" src="libs/chardet/utf8prober.py" />
        <File name="version" src="libs/chardet/version.py" />
        <File name="DESCRIPTION" src="libs/idna-2.6.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/idna-2.6.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/idna-2.6.dist-info/METADATA" />
        <File name="RECORD" src="libs/idna-2.6.dist-info/RECORD" />
        <File name="WHEEL" src="libs/idna-2.6.dist-info/WHEEL" />
        <File name="metadata" src="libs/idna-2.6.dist-info/metadata.json" />
        <File name="top_level" src="libs/idna-2.6.dist-info/top_level.txt" />
        <File name="__init__" src="libs/idna/__init__.py" />
        <File name="codec" src="libs/idna/codec.py" />
        <File name="compat" src="libs/idna/compat.py" />
        <File name="core" src="libs/idna/core.py" />
        <File name="idnadata" src="libs/idna/idnadata.py" />
        <File name="intranges" src="libs/idna/intranges.py" />
        <File name="package_data" src="libs/idna/package_data.py" />
        <File name="uts46data" src="libs/idna/uts46data.py" />
        <File name="DESCRIPTION" src="libs/requests-2.18.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/requests-2.18.4.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/requests-2.18.4.dist-info/METADATA" />
        <File name="RECORD" src="libs/requests-2.18.4.dist-info/RECORD" />
        <File name="WHEEL" src="libs/requests-2.18.4.dist-info/WHEEL" />
        <File name="metadata" src="libs/requests-2.18.4.dist-info/metadata.json" />
        <File name="top_level" src="libs/requests-2.18.4.dist-info/top_level.txt" />
        <File name="__init__" src="libs/requests/__init__.py" />
        <File name="__version__" src="libs/requests/__version__.py" />
        <File name="_internal_utils" src="libs/requests/_internal_utils.py" />
        <File name="adapters" src="libs/requests/adapters.py" />
        <File name="api" src="libs/requests/api.py" />
        <File name="auth" src="libs/requests/auth.py" />
        <File name="certs" src="libs/requests/certs.py" />
        <File name="compat" src="libs/requests/compat.py" />
        <File name="cookies" src="libs/requests/cookies.py" />
        <File name="exceptions" src="libs/requests/exceptions.py" />
        <File name="help" src="libs/requests/help.py" />
        <File name="hooks" src="libs/requests/hooks.py" />
        <File name="models" src="libs/requests/models.py" />
        <File name="packages" src="libs/requests/packages.py" />
        <File name="sessions" src="libs/requests/sessions.py" />
        <File name="status_codes" src="libs/requests/status_codes.py" />
        <File name="structures" src="libs/requests/structures.py" />
        <File name="utils" src="libs/requests/utils.py" />
        <File name="six" src="libs/six.py" />
        <File name="PKG-INFO" src="libs/slackclient-1.0.9-py2.7.egg-info/PKG-INFO" />
        <File name="SOURCES" src="libs/slackclient-1.0.9-py2.7.egg-info/SOURCES.txt" />
        <File name="dependency_links" src="libs/slackclient-1.0.9-py2.7.egg-info/dependency_links.txt" />
        <File name="installed-files" src="libs/slackclient-1.0.9-py2.7.egg-info/installed-files.txt" />
        <File name="requires" src="libs/slackclient-1.0.9-py2.7.egg-info/requires.txt" />
        <File name="top_level" src="libs/slackclient-1.0.9-py2.7.egg-info/top_level.txt" />
        <File name="__init__" src="libs/slackclient/__init__.py" />
        <File name="channel" src="libs/slackclient/channel.py" />
        <File name="client" src="libs/slackclient/client.py" />
        <File name="im" src="libs/slackclient/im.py" />
        <File name="server" src="libs/slackclient/server.py" />
        <File name="slackrequest" src="libs/slackclient/slackrequest.py" />
        <File name="user" src="libs/slackclient/user.py" />
        <File name="util" src="libs/slackclient/util.py" />
        <File name="version" src="libs/slackclient/version.py" />
        <File name="DESCRIPTION" src="libs/urllib3-1.22.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/urllib3-1.22.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/urllib3-1.22.dist-info/METADATA" />
        <File name="RECORD" src="libs/urllib3-1.22.dist-info/RECORD" />
        <File name="WHEEL" src="libs/urllib3-1.22.dist-info/WHEEL" />
        <File name="metadata" src="libs/urllib3-1.22.dist-info/metadata.json" />
        <File name="top_level" src="libs/urllib3-1.22.dist-info/top_level.txt" />
        <File name="__init__" src="libs/urllib3/__init__.py" />
        <File name="_collections" src="libs/urllib3/_collections.py" />
        <File name="connection" src="libs/urllib3/connection.py" />
        <File name="connectionpool" src="libs/urllib3/connectionpool.py" />
        <File name="__init__" src="libs/urllib3/contrib/__init__.py" />
        <File name="__init__" src="libs/urllib3/contrib/_securetransport/__init__.py" />
        <File name="bindings" src="libs/urllib3/contrib/_securetransport/bindings.py" />
        <File name="low_level" src="libs/urllib3/contrib/_securetransport/low_level.py" />
        <File name="appengine" src="libs/urllib3/contrib/appengine.py" />
        <File name="ntlmpool" src="libs/urllib3/contrib/ntlmpool.py" />
        <File name="pyopenssl" src="libs/urllib3/contrib/pyopenssl.py" />
        <File name="securetransport" src="libs/urllib3/contrib/securetransport.py" />
        <File name="socks" src="libs/urllib3/contrib/socks.py" />
        <File name="exceptions" src="libs/urllib3/exceptions.py" />
        <File name="fields" src="libs/urllib3/fields.py" />
        <File name="filepost" src="libs/urllib3/filepost.py" />
        <File name="__init__" src="libs/urllib3/packages/__init__.py" />
        <File name="__init__" src="libs/urllib3/packages/backports/__init__.py" />
        <File name="makefile" src="libs/urllib3/packages/backports/makefile.py" />
        <File name="ordered_dict" src="libs/urllib3/packages/ordered_dict.py" />
        <File name="six" src="libs/urllib3/packages/six.py" />
        <File name="__init__" src="libs/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="_implementation" src="libs/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="poolmanager" src="libs/urllib3/poolmanager.py" />
        <File name="request" src="libs/urllib3/request.py" />
        <File name="response" src="libs/urllib3/response.py" />
        <File name="__init__" src="libs/urllib3/util/__init__.py" />
        <File name="connection" src="libs/urllib3/util/connection.py" />
        <File name="request" src="libs/urllib3/util/request.py" />
        <File name="response" src="libs/urllib3/util/response.py" />
        <File name="retry" src="libs/urllib3/util/retry.py" />
        <File name="selectors" src="libs/urllib3/util/selectors.py" />
        <File name="ssl_" src="libs/urllib3/util/ssl_.py" />
        <File name="timeout" src="libs/urllib3/util/timeout.py" />
        <File name="url" src="libs/urllib3/util/url.py" />
        <File name="wait" src="libs/urllib3/util/wait.py" />
        <File name="__init__" src="libs/websocket/__init__.py" />
        <File name="_abnf" src="libs/websocket/_abnf.py" />
        <File name="_app" src="libs/websocket/_app.py" />
        <File name="_cookiejar" src="libs/websocket/_cookiejar.py" />
        <File name="_core" src="libs/websocket/_core.py" />
        <File name="_exceptions" src="libs/websocket/_exceptions.py" />
        <File name="_handshake" src="libs/websocket/_handshake.py" />
        <File name="_http" src="libs/websocket/_http.py" />
        <File name="_logging" src="libs/websocket/_logging.py" />
        <File name="_socket" src="libs/websocket/_socket.py" />
        <File name="_ssl_compat" src="libs/websocket/_ssl_compat.py" />
        <File name="_url" src="libs/websocket/_url.py" />
        <File name="_utils" src="libs/websocket/_utils.py" />
        <File name="cacert" src="libs/websocket/cacert.pem" />
        <File name="__init__" src="libs/websocket/tests/__init__.py" />
        <File name="header01" src="libs/websocket/tests/data/header01.txt" />
        <File name="header02" src="libs/websocket/tests/data/header02.txt" />
        <File name="test_cookiejar" src="libs/websocket/tests/test_cookiejar.py" />
        <File name="test_websocket" src="libs/websocket/tests/test_websocket.py" />
        <File name="DESCRIPTION" src="libs/websocket_client-0.44.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/websocket_client-0.44.0.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/websocket_client-0.44.0.dist-info/METADATA" />
        <File name="RECORD" src="libs/websocket_client-0.44.0.dist-info/RECORD" />
        <File name="WHEEL" src="libs/websocket_client-0.44.0.dist-info/WHEEL" />
        <File name="metadata" src="libs/websocket_client-0.44.0.dist-info/metadata.json" />
        <File name="top_level" src="libs/websocket_client-0.44.0.dist-info/top_level.txt" />
        <File name="DESCRIPTION" src="libs/six-1.11.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="libs/six-1.11.0.dist-info/INSTALLER" />
        <File name="METADATA" src="libs/six-1.11.0.dist-info/METADATA" />
        <File name="RECORD" src="libs/six-1.11.0.dist-info/RECORD" />
        <File name="WHEEL" src="libs/six-1.11.0.dist-info/WHEEL" />
        <File name="metadata" src="libs/six-1.11.0.dist-info/metadata.json" />
        <File name="top_level" src="libs/six-1.11.0.dist-info/top_level.txt" />
    </Resources>
    <Topics>
        <Topic name="interaction_jpj" src="dialog/interaction/interaction_jpj.top" topicName="interaction" language="ja_JP" />
    </Topics>
    <IgnoredPaths />
    <Translations auto-fill="ja_JP">
        <Translation name="translation_ja_JP" src="translations/translation_ja_JP.ts" language="ja_JP" />
    </Translations>
</Package>
